image:
  file: .gitpod.dockerfile
tasks:
 - init: . ${GITPOD_REPO_ROOT}/.theia/init_tasks.sh    
vscode:
  extensions:
    - formulahendry.auto-close-tag
    - eamodio.gitlens
    - abusaidm.html-snippets
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - zhuangtongfa.material-theme
    - esbenp.prettier-vscode
    - ms-python.python
